export interface Ingredient {
  id: string;
  name: string;
  emoji: string;
  category?: string;
}

export const LIQUORS: Ingredient[] = [
  { id: "vodka", name: "Vodka", emoji: "🍸" },
  { id: "rum", name: "Rum", emoji: "🏝️" },
  { id: "gin", name: "Gin", emoji: "🌿" },
  { id: "tequila", name: "Tequila", emoji: "🌵" },
  { id: "whiskey", name: "Whiskey", emoji: "🥃" },
  { id: "bourbon", name: "Bourbon", emoji: "🥃" },
  { id: "scotch", name: "Scotch", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
  { id: "brandy", name: "Brandy", emoji: "🍷" },
  { id: "cognac", name: "Cognac", emoji: "🍷" },
  { id: "champagne", name: "Champagne", emoji: "🥂" },
  { id: "prosecco", name: "Prosecco", emoji: "🥂" },
  { id: "wine-red", name: "Red Wine", emoji: "🍷" },
  { id: "wine-white", name: "White Wine", emoji: "🥂" },
  { id: "beer", name: "Beer", emoji: "🍺" },
  { id: "triple-sec", name: "Triple Sec", emoji: "🍊" },
  { id: "kahlua", name: "Kahlúa", emoji: "☕" },
  { id: "baileys", name: "Baileys", emoji: "🥛" },
  { id: "amaretto", name: "Amaretto", emoji: "🌰" },
  { id: "peach-schnapps", name: "Peach Schnapps", emoji: "🍑" },
  { id: "blue-curacao", name: "Blue Curaçao", emoji: "💙" },
  { id: "midori", name: "Midori", emoji: "🍈" },
  { id: "absinthe", name: "Absinthe", emoji: "🟢" },
  { id: "mezcal", name: "Mezcal", emoji: "🌵" },
  { id: "dark-rum", name: "Dark Rum", emoji: "🍫" },
  { id: "spiced-rum", name: "Spiced Rum", emoji: "🌶️" },
  { id: "white-rum", name: "White Rum", emoji: "🤍" },
  { id: "sake", name: "Sake", emoji: "🍶" },
  { id: "vermouth-dry", name: "Dry Vermouth", emoji: "🍸" },
  { id: "vermouth-sweet", name: "Sweet Vermouth", emoji: "🍷" },
  { id: "campari", name: "Campari", emoji: "🔴" },
  { id: "aperol", name: "Aperol", emoji: "🟠" },
];

export const TOP_LIQUORS = [
  "vodka",
  "rum",
  "gin",
  "tequila",
  "whiskey",
  "bourbon",
  "champagne",
  "triple-sec",
];

export const MIXERS: Ingredient[] = [
  { id: "soda-water", name: "Soda Water", emoji: "💧" },
  { id: "tonic-water", name: "Tonic Water", emoji: "🫧" },
  { id: "cola", name: "Cola", emoji: "🥤" },
  { id: "ginger-beer", name: "Ginger Beer", emoji: "🫚" },
  { id: "ginger-ale", name: "Ginger Ale", emoji: "🟡" },
  { id: "orange-juice", name: "Orange Juice", emoji: "🍊" },
  { id: "pineapple-juice", name: "Pineapple Juice", emoji: "🍍" },
  { id: "cranberry-juice", name: "Cranberry Juice", emoji: "🫐" },
  { id: "lime-juice", name: "Lime Juice", emoji: "🍋" },
  { id: "lemon-juice", name: "Lemon Juice", emoji: "🍋‍🟩" },
  { id: "grapefruit-juice", name: "Grapefruit Juice", emoji: "🍊" },
  { id: "apple-juice", name: "Apple Juice", emoji: "🍎" },
  { id: "coconut-cream", name: "Coconut Cream", emoji: "🥥" },
  { id: "coconut-water", name: "Coconut Water", emoji: "🥥" },
  { id: "mango-juice", name: "Mango Juice", emoji: "🥭" },
  { id: "passion-fruit-juice", name: "Passion Fruit Juice", emoji: "💜" },
  { id: "grenadine", name: "Grenadine", emoji: "🔴" },
  { id: "simple-syrup", name: "Simple Syrup", emoji: "🍯" },
  { id: "agave-syrup", name: "Agave Syrup", emoji: "🌵" },
  { id: "honey", name: "Honey", emoji: "🍯" },
  { id: "cream", name: "Cream", emoji: "🥛" },
  { id: "milk", name: "Milk", emoji: "🥛" },
  { id: "almond-milk", name: "Almond Milk", emoji: "🌰" },
  { id: "tomato-juice", name: "Tomato Juice", emoji: "🍅" },
  { id: "espresso", name: "Espresso", emoji: "☕" },
  { id: "cold-brew", name: "Cold Brew Coffee", emoji: "☕" },
  { id: "lemonade", name: "Lemonade", emoji: "🍋" },
  { id: "iced-tea", name: "Iced Tea", emoji: "🍵" },
  { id: "blue-curacao-mixer", name: "Blue Curaçao Syrup", emoji: "💙" },
  { id: "elderflower", name: "Elderflower Cordial", emoji: "🌸" },
];

export const TOP_MIXERS = [
  "soda-water",
  "tonic-water",
  "cola",
  "orange-juice",
  "lime-juice",
  "ginger-beer",
  "cranberry-juice",
  "pineapple-juice",
];

export const EXTRAS: Ingredient[] = [
  // Fruits
  { id: "lime", name: "Lime", emoji: "🍋", category: "Fruit" },
  { id: "lemon", name: "Lemon", emoji: "🍋‍🟩", category: "Fruit" },
  { id: "orange", name: "Orange", emoji: "🍊", category: "Fruit" },
  { id: "strawberry", name: "Strawberry", emoji: "🍓", category: "Fruit" },
  { id: "raspberry", name: "Raspberry", emoji: "🫐", category: "Fruit" },
  { id: "blueberry", name: "Blueberry", emoji: "🫐", category: "Fruit" },
  { id: "blackberry", name: "Blackberry", emoji: "🫐", category: "Fruit" },
  { id: "mango", name: "Mango", emoji: "🥭", category: "Fruit" },
  { id: "pineapple", name: "Pineapple", emoji: "🍍", category: "Fruit" },
  { id: "watermelon", name: "Watermelon", emoji: "🍉", category: "Fruit" },
  { id: "peach", name: "Peach", emoji: "🍑", category: "Fruit" },
  { id: "passion-fruit", name: "Passion Fruit", emoji: "💜", category: "Fruit" },
  { id: "kiwi", name: "Kiwi", emoji: "🥝", category: "Fruit" },
  { id: "cherry", name: "Cherry", emoji: "🍒", category: "Fruit" },
  { id: "grape", name: "Grape", emoji: "🍇", category: "Fruit" },
  { id: "apple", name: "Apple", emoji: "🍎", category: "Fruit" },
  { id: "cucumber", name: "Cucumber", emoji: "🥒", category: "Vegetable" },
  { id: "celery", name: "Celery", emoji: "🥬", category: "Vegetable" },
  { id: "jalapeno", name: "Jalapeño", emoji: "🌶️", category: "Vegetable" },
  // Herbs & Spices
  { id: "mint", name: "Fresh Mint", emoji: "🌿", category: "Herb" },
  { id: "basil", name: "Fresh Basil", emoji: "🌿", category: "Herb" },
  { id: "rosemary", name: "Rosemary", emoji: "🌿", category: "Herb" },
  { id: "thyme", name: "Thyme", emoji: "🌿", category: "Herb" },
  { id: "ginger", name: "Fresh Ginger", emoji: "🫚", category: "Spice" },
  { id: "cinnamon", name: "Cinnamon", emoji: "🟤", category: "Spice" },
  { id: "cardamom", name: "Cardamom", emoji: "🟢", category: "Spice" },
  { id: "chili", name: "Chili", emoji: "🌶️", category: "Spice" },
  { id: "black-pepper", name: "Black Pepper", emoji: "🖤", category: "Spice" },
  { id: "salt", name: "Salt (rim)", emoji: "🧂", category: "Garnish" },
  { id: "sugar", name: "Sugar (rim)", emoji: "🤍", category: "Garnish" },
  // Extras
  { id: "egg-white", name: "Egg White", emoji: "🥚", category: "Extra" },
  { id: "coconut-flakes", name: "Coconut Flakes", emoji: "🥥", category: "Extra" },
  { id: "vanilla", name: "Vanilla Extract", emoji: "🌰", category: "Extra" },
  { id: "chocolate-bitters", name: "Chocolate Bitters", emoji: "🍫", category: "Extra" },
  { id: "angostura-bitters", name: "Angostura Bitters", emoji: "🫙", category: "Extra" },
  { id: "orange-bitters", name: "Orange Bitters", emoji: "🍊", category: "Extra" },
  { id: "activated-charcoal", name: "Activated Charcoal", emoji: "⚫", category: "Extra" },
  { id: "matcha", name: "Matcha Powder", emoji: "🟢", category: "Extra" },
  { id: "turmeric", name: "Turmeric", emoji: "🟡", category: "Extra" },
];

export const TOP_EXTRAS = [
  "lime",
  "lemon",
  "mint",
  "strawberry",
  "ginger",
  "orange",
  "cucumber",
  "egg-white",
];
